### ISSUE TITLE
Trouble running the PicoWeb examples when using utemplate

### ISSUE THREAD

**Issue by joewez** [pfalcon/utemplate#9] opened 2017-12-01 03:48 UTC
**I have frozen PicoWeb (and uasyncio) into and ESP8266 firmware bin.  Then I added utemplate, the templates directory with squares.tpl and example_webapp.py.  On first run I get this...**

`
33.000 <HTTPRequest object at 3fff36f0> <StreamWriter <socket state=2 timeout=0 incoming=3fff91d8 off=23>> "GET /squares"

33.000 <HTTPRequest object at 3fff36f0> <StreamWriter <socket state=2 timeout=0 incoming=0 off=0>> AttributeError("'module' object has no attribute '__path__'",)
Traceback (most recent call last):

  File "picoweb/__init__.py", line 188, in _handle

  File "example_webapp.py", line 22, in squares

  File "picoweb/__init__.py", line 231, in render_template

  File "picoweb/__init__.py", line 227, in _load_template

  File "utemplate/source.py", line 153, in __init__

AttributeError: 'module' object has no attribute '__path__'
`

**If I add a __path__ declaration to example_webapp.py I get this...**

`
133.999 <HTTPRequest object at 3fff4c80> <StreamWriter <socket state=2 timeout=0 incoming=3fff91d8 off=23>> "GET /squares"

136.000 <HTTPRequest object at 3fff4c80> <StreamWriter <socket state=2 timeout=0 incoming=0 off=0>> ImportError("no module named 'example_webapp.templates'",)
Traceback (most recent call last):

  File "picoweb/__init__.py", line 188, in _handle

  File "example_webapp.py", line 24, in squares

  File "picoweb/__init__.py", line 231, in render_template

  File "picoweb/__init__.py", line 228, in _load_template

  File "utemplate/source.py", line 182, in load

  File "utemplate/compiled.py", line 14, in load

ImportError: no module named 'example_webapp.templates'
`

Everything else works as expected so I think the problem is specifically with utemplate.

**Comment by pfalcon** [comment] 2017-12-01 13:07
This seems to be duplicate of  https://github.com/pfalcon/picoweb/issues/15 . The examples distributed with Picoweb are originally intended to run with Unix port, and apparently need tweaking for no-command-line environments.

If you want to see an example which guaranteedly runs on esp8266, it's https://github.com/pfalcon/notes-pico (follow its instructions!).

**Closed as completed by pfalcon** 2017-12-01 13:07 UTC
